// import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
import './main.css'
export const metadata = {
  title: 'Allen Greenwood',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='body'>{children}</body>
    </html>
  )
}
